preset: laravel
risky: true

enabled:
  - alpha_ordered_imports
  - align_double_arrow
  - align_equals
  - ordered_class_elements
  - phpdoc_add_missing_param_annotation
  - is_null

disabled:
  - unalign_equals

finder:
  exclude:
    - "tests"
    - "node_modules"
    - "storage"
    - "vendor"
  not-name:
    - "AcceptanceTester.php"
    - "FunctionalTester.php"
    - "UnitTester.php"
